# Generated by Django 3.2.6 on 2023-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(max_length=100)),
                ('NameOfAccount_Manager', models.CharField(max_length=200)),
                ('VPC', models.CharField(max_length=20)),
                ('UIGmigs', models.CharField(max_length=20)),
                ('Billing', models.IntegerField()),
                ('CF', models.CharField(max_length=20)),
                ('Salfny', models.CharField(max_length=20)),
                ('Lending', models.CharField(max_length=20)),
                ('TrxLastMonth', models.CharField(max_length=20)),
                ('TrxCurrentMonth', models.CharField(max_length=20)),
                ('VolumeLastMonth', models.CharField(max_length=20)),
                ('VolumeCurrentMonth', models.CharField(max_length=20)),
                ('ChurnType', models.CharField(max_length=20)),
                ('ChurnVolume', models.CharField(max_length=20)),
                ('ActiveTarget', models.CharField(max_length=20)),
                ('Current_MonthTarget', models.CharField(max_length=20)),
                ('Pre_MonthTarget', models.CharField(max_length=20)),
            ],
        ),
    ]
