# Generated by Django 3.2.6 on 2023-05-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='CF',
            new_name='CF_value',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='VPC',
            new_name='VPC_value',
        ),
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
