# Generated by Django 3.2.6 on 2023-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230508_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='ActiveTarget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Billing',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='CF_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='ChurnType',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='ChurnVolume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Lending',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Salfny',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='TrxCurrentMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='TrxLastMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='UIGmigs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='VPC_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='VolumeCurrentMonth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='VolumeLastMonth',
            field=models.IntegerField(),
        ),
    ]
